spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/msaproject  # MySQL 데이터베이스 URL
    username: root  # MySQL 사용자 이름
    password: 1234  # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 테이블 자동 생성 및 업데이트 설정
    show-sql: true  # SQL 쿼리 로그 출력 여부

server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
